# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'config.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QHeaderView, QLabel, QMainWindow, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpinBox, QStackedWidget, QStatusBar, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(40, 30, 721, 491))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.startButton = QPushButton(self.page)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(340, 350, 91, 41))
        self.settingsButton = QPushButton(self.page)
        self.settingsButton.setObjectName(u"settingsButton")
        self.settingsButton.setGeometry(QRect(510, 290, 141, 41))
        self.reinforcementButton = QPushButton(self.page)
        self.reinforcementButton.setObjectName(u"reinforcementButton")
        self.reinforcementButton.setGeometry(QRect(510, 240, 141, 41))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.SaveButton = QPushButton(self.page_2)
        self.SaveButton.setObjectName(u"SaveButton")
        self.SaveButton.setGeometry(QRect(370, 430, 101, 41))
        self.MenuButton = QPushButton(self.page_2)
        self.MenuButton.setObjectName(u"MenuButton")
        self.MenuButton.setGeometry(QRect(260, 430, 101, 41))
        self.FloorsSpinBox = QSpinBox(self.page_2)
        self.FloorsSpinBox.setObjectName(u"FloorsSpinBox")
        self.FloorsSpinBox.setGeometry(QRect(70, 50, 81, 31))
        self.FloorsSpinBox.setMinimum(2)
        self.FloorsSpinBox.setMaximum(20)
        self.FloorsSpinBox.setValue(5)
        self.label = QLabel(self.page_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(70, 30, 101, 16))
        self.StepsHorizontalSlider = QSlider(self.page_2)
        self.StepsHorizontalSlider.setObjectName(u"StepsHorizontalSlider")
        self.StepsHorizontalSlider.setGeometry(QRect(70, 120, 261, 18))
        self.StepsHorizontalSlider.setMinimumSize(QSize(160, 0))
        self.StepsHorizontalSlider.setMinimum(100)
        self.StepsHorizontalSlider.setMaximum(10000)
        self.StepsHorizontalSlider.setSliderPosition(1000)
        self.StepsHorizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.label_2 = QLabel(self.page_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 100, 101, 16))
        self.MaxPeopleFloorSpinBox = QSpinBox(self.page_2)
        self.MaxPeopleFloorSpinBox.setObjectName(u"MaxPeopleFloorSpinBox")
        self.MaxPeopleFloorSpinBox.setGeometry(QRect(70, 170, 81, 31))
        self.label_3 = QLabel(self.page_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 150, 221, 16))
        self.VisualisationRadioButton = QRadioButton(self.page_2)
        self.VisualisationRadioButton.setObjectName(u"VisualisationRadioButton")
        self.VisualisationRadioButton.setGeometry(QRect(70, 220, 92, 20))
        self.ElevatorTable = QTableWidget(self.page_2)
        if (self.ElevatorTable.columnCount() < 3):
            self.ElevatorTable.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.ElevatorTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.ElevatorTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.ElevatorTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.ElevatorTable.setObjectName(u"ElevatorTable")
        self.ElevatorTable.setGeometry(QRect(370, 120, 311, 181))
        self.ElevatorsSpinBox = QSpinBox(self.page_2)
        self.ElevatorsSpinBox.setObjectName(u"ElevatorsSpinBox")
        self.ElevatorsSpinBox.setGeometry(QRect(370, 50, 71, 31))
        self.ElevatorsSpinBox.setMinimum(1)
        self.ElevatorsSpinBox.setMaximum(8)
        self.ElevatorsSpinBox.setValue(2)
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(370, 30, 121, 16))
        self.AlgorithmComboBox = QComboBox(self.page_2)
        self.AlgorithmComboBox.setObjectName(u"AlgorithmComboBox")
        self.AlgorithmComboBox.setGeometry(QRect(70, 270, 161, 24))
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 250, 221, 16))
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(70, 300, 221, 16))
        self.ModelComboBox = QComboBox(self.page_2)
        self.ModelComboBox.setObjectName(u"ModelComboBox")
        self.ModelComboBox.setGeometry(QRect(70, 320, 161, 24))
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(70, 350, 221, 16))
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(70, 370, 41, 16))
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(140, 370, 51, 16))
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(120, 370, 16, 16))
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(200, 370, 16, 16))
        self.TrafficConfigurationButton = QPushButton(self.page_2)
        self.TrafficConfigurationButton.setObjectName(u"TrafficConfigurationButton")
        self.TrafficConfigurationButton.setGeometry(QRect(370, 320, 131, 31))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 20, 191, 61))
        font = QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.MenuButton_2 = QPushButton(self.page_3)
        self.MenuButton_2.setObjectName(u"MenuButton_2")
        self.MenuButton_2.setGeometry(QRect(260, 430, 101, 41))
        self.up_peak_button = QRadioButton(self.page_3)
        self.up_peak_button.setObjectName(u"up_peak_button")
        self.up_peak_button.setGeometry(QRect(80, 120, 92, 20))
        self.down_peak_button = QRadioButton(self.page_3)
        self.down_peak_button.setObjectName(u"down_peak_button")
        self.down_peak_button.setGeometry(QRect(80, 150, 92, 20))
        self.mixed_peak_button = QRadioButton(self.page_3)
        self.mixed_peak_button.setObjectName(u"mixed_peak_button")
        self.mixed_peak_button.setGeometry(QRect(80, 180, 92, 20))
        self.label_14 = QLabel(self.page_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(80, 90, 131, 16))
        self.intensitySpinBox = QDoubleSpinBox(self.page_3)
        self.intensitySpinBox.setObjectName(u"intensitySpinBox")
        self.intensitySpinBox.setGeometry(QRect(290, 120, 84, 23))
        self.intensitySpinBox.setDecimals(4)
        self.intensitySpinBox.setSingleStep(0.010000000000000)
        self.intensitySpinBox.setValue(0.050000000000000)
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(230, 120, 50, 20))
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(230, 90, 161, 16))
        self.SaveButton_2 = QPushButton(self.page_3)
        self.SaveButton_2.setObjectName(u"SaveButton_2")
        self.SaveButton_2.setGeometry(QRect(370, 430, 101, 41))
        self.back_to_config_button = QPushButton(self.page_3)
        self.back_to_config_button.setObjectName(u"back_to_config_button")
        self.back_to_config_button.setGeometry(QRect(80, 40, 79, 24))
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(230, 150, 49, 16))
        self.seedSpinBox = QSpinBox(self.page_3)
        self.seedSpinBox.setObjectName(u"seedSpinBox")
        self.seedSpinBox.setGeometry(QRect(350, 150, 71, 20))
        self.traffic_stacked_widget = QStackedWidget(self.page_3)
        self.traffic_stacked_widget.setObjectName(u"traffic_stacked_widget")
        self.traffic_stacked_widget.setGeometry(QRect(420, 90, 261, 281))
        self.up_peak_page = QWidget()
        self.up_peak_page.setObjectName(u"up_peak_page")
        self.label_18 = QLabel(self.up_peak_page)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 20, 71, 16))
        self.arrval_floor_spin_box = QSpinBox(self.up_peak_page)
        self.arrval_floor_spin_box.setObjectName(u"arrval_floor_spin_box")
        self.arrval_floor_spin_box.setGeometry(QRect(90, 18, 51, 20))
        self.tableWidget = QTableWidget(self.up_peak_page)
        if (self.tableWidget.columnCount() < 2):
            self.tableWidget.setColumnCount(2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 50, 241, 201))
        self.traffic_stacked_widget.addWidget(self.up_peak_page)
        self.down_peak_page = QWidget()
        self.down_peak_page.setObjectName(u"down_peak_page")
        self.label_19 = QLabel(self.down_peak_page)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 21, 101, 16))
        self.destination_floor_spin_box = QSpinBox(self.down_peak_page)
        self.destination_floor_spin_box.setObjectName(u"destination_floor_spin_box")
        self.destination_floor_spin_box.setGeometry(QRect(110, 20, 51, 20))
        self.traffic_stacked_widget.addWidget(self.down_peak_page)
        self.mixed_peak_page = QWidget()
        self.mixed_peak_page.setObjectName(u"mixed_peak_page")
        self.arrival_floor_spin_box_2 = QSpinBox(self.mixed_peak_page)
        self.arrival_floor_spin_box_2.setObjectName(u"arrival_floor_spin_box_2")
        self.arrival_floor_spin_box_2.setGeometry(QRect(110, 19, 51, 20))
        self.label_20 = QLabel(self.mixed_peak_page)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 20, 101, 16))
        self.destination_floor_spin_box_2 = QSpinBox(self.mixed_peak_page)
        self.destination_floor_spin_box_2.setObjectName(u"destination_floor_spin_box_2")
        self.destination_floor_spin_box_2.setGeometry(QRect(110, 50, 51, 20))
        self.label_21 = QLabel(self.mixed_peak_page)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 51, 101, 16))
        self.mixed_up_peak_ratio_spinbox = QDoubleSpinBox(self.mixed_peak_page)
        self.mixed_up_peak_ratio_spinbox.setObjectName(u"mixed_up_peak_ratio_spinbox")
        self.mixed_up_peak_ratio_spinbox.setGeometry(QRect(90, 120, 84, 23))
        self.mixed_up_peak_ratio_spinbox.setMaximum(1.000000000000000)
        self.mixed_up_peak_ratio_spinbox.setSingleStep(0.100000000000000)
        self.mixed_down_peak_ratio_spinbox = QDoubleSpinBox(self.mixed_peak_page)
        self.mixed_down_peak_ratio_spinbox.setObjectName(u"mixed_down_peak_ratio_spinbox")
        self.mixed_down_peak_ratio_spinbox.setGeometry(QRect(90, 150, 84, 23))
        self.mixed_down_peak_ratio_spinbox.setMaximum(1.000000000000000)
        self.mixed_down_peak_ratio_spinbox.setSingleStep(0.100000000000000)
        self.mixed_interfloor_peak_ratio_spinbox = QDoubleSpinBox(self.mixed_peak_page)
        self.mixed_interfloor_peak_ratio_spinbox.setObjectName(u"mixed_interfloor_peak_ratio_spinbox")
        self.mixed_interfloor_peak_ratio_spinbox.setGeometry(QRect(90, 180, 84, 23))
        self.mixed_interfloor_peak_ratio_spinbox.setMaximum(1.000000000000000)
        self.mixed_interfloor_peak_ratio_spinbox.setSingleStep(0.100000000000000)
        self.label_22 = QLabel(self.mixed_peak_page)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(60, 100, 41, 16))
        self.label_23 = QLabel(self.mixed_peak_page)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(8, 120, 71, 20))
        self.label_24 = QLabel(self.mixed_peak_page)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(8, 150, 71, 20))
        self.label_25 = QLabel(self.mixed_peak_page)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(8, 180, 71, 20))
        self.traffic_stacked_widget.addWidget(self.mixed_peak_page)
        self.randomButton = QCheckBox(self.page_3)
        self.randomButton.setObjectName(u"randomButton")
        self.randomButton.setGeometry(QRect(280, 150, 71, 20))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_13 = QLabel(self.page_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(270, 30, 171, 61))
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.settingsButton_2 = QPushButton(self.page_4)
        self.settingsButton_2.setObjectName(u"settingsButton_2")
        self.settingsButton_2.setGeometry(QRect(140, 400, 141, 41))
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(2)
        self.traffic_stacked_widget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.startButton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.settingsButton.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.reinforcementButton.setText(QCoreApplication.translate("MainWindow", u"Reinforcement Learning", None))
        self.SaveButton.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.MenuButton.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Number of floors", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Simulation steps", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Maximum number of people at the floor", None))
        self.VisualisationRadioButton.setText(QCoreApplication.translate("MainWindow", u"Visualisation", None))
        ___qtablewidgetitem = self.ElevatorTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Max people", None));
        ___qtablewidgetitem1 = self.ElevatorTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Speed", None));
        ___qtablewidgetitem2 = self.ElevatorTable.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Max floor", None));
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Number of elevators", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"AlgorithmEnum", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Model parameters:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Floors: ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Elevators:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u2013", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u2013", None))
        self.TrafficConfigurationButton.setText(QCoreApplication.translate("MainWindow", u"Traffic Configuration", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Traffic Configuration Panel", None))
        self.MenuButton_2.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.up_peak_button.setText(QCoreApplication.translate("MainWindow", u"Up-peak", None))
        self.down_peak_button.setText(QCoreApplication.translate("MainWindow", u"Down-peak", None))
        self.mixed_peak_button.setText(QCoreApplication.translate("MainWindow", u"Mixed-peak", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Traffic generation type:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Intensity:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Traffic generation parameters:", None))
        self.SaveButton_2.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.back_to_config_button.setText(QCoreApplication.translate("MainWindow", u"\u2190 Back", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Seed:", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Arrival floor:", None))
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Floor", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Distribution", None));
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Destination floor:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Arrival floor:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Destination floor:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Ratios:", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Up-peak:", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Down-peak:", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Interfloor:", None))
        self.randomButton.setText(QCoreApplication.translate("MainWindow", u"random", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Reinforcement Learning", None))
        self.settingsButton_2.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

