# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'config.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFrame, QHeaderView, QLabel, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpinBox, QStackedWidget, QStatusBar, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(40, 30, 721, 491))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.startButton = QPushButton(self.page)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(340, 350, 91, 41))
        self.settingsButton = QPushButton(self.page)
        self.settingsButton.setObjectName(u"settingsButton")
        self.settingsButton.setGeometry(QRect(510, 290, 141, 41))
        self.reinforcementButton = QPushButton(self.page)
        self.reinforcementButton.setObjectName(u"reinforcementButton")
        self.reinforcementButton.setGeometry(QRect(510, 240, 141, 41))
        self.analysePushButton = QPushButton(self.page)
        self.analysePushButton.setObjectName(u"analysePushButton")
        self.analysePushButton.setGeometry(QRect(510, 190, 141, 41))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.SaveButton = QPushButton(self.page_2)
        self.SaveButton.setObjectName(u"SaveButton")
        self.SaveButton.setGeometry(QRect(370, 430, 101, 41))
        self.MenuButton = QPushButton(self.page_2)
        self.MenuButton.setObjectName(u"MenuButton")
        self.MenuButton.setGeometry(QRect(260, 430, 101, 41))
        self.FloorsSpinBox = QSpinBox(self.page_2)
        self.FloorsSpinBox.setObjectName(u"FloorsSpinBox")
        self.FloorsSpinBox.setGeometry(QRect(70, 50, 81, 31))
        self.FloorsSpinBox.setMinimum(2)
        self.FloorsSpinBox.setMaximum(20)
        self.FloorsSpinBox.setValue(5)
        self.label = QLabel(self.page_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(70, 30, 101, 16))
        self.StepsHorizontalSlider = QSlider(self.page_2)
        self.StepsHorizontalSlider.setObjectName(u"StepsHorizontalSlider")
        self.StepsHorizontalSlider.setGeometry(QRect(70, 120, 221, 18))
        self.StepsHorizontalSlider.setMinimumSize(QSize(160, 0))
        self.StepsHorizontalSlider.setMinimum(100)
        self.StepsHorizontalSlider.setMaximum(50000)
        self.StepsHorizontalSlider.setSingleStep(100)
        self.StepsHorizontalSlider.setPageStep(1)
        self.StepsHorizontalSlider.setSliderPosition(1000)
        self.StepsHorizontalSlider.setOrientation(Qt.Orientation.Horizontal)
        self.label_2 = QLabel(self.page_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 100, 101, 16))
        self.MaxPeopleFloorSpinBox = QSpinBox(self.page_2)
        self.MaxPeopleFloorSpinBox.setObjectName(u"MaxPeopleFloorSpinBox")
        self.MaxPeopleFloorSpinBox.setGeometry(QRect(70, 170, 81, 31))
        self.label_3 = QLabel(self.page_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 150, 221, 16))
        self.VisualisationRadioButton = QRadioButton(self.page_2)
        self.VisualisationRadioButton.setObjectName(u"VisualisationRadioButton")
        self.VisualisationRadioButton.setGeometry(QRect(70, 220, 92, 20))
        self.ElevatorTable = QTableWidget(self.page_2)
        if (self.ElevatorTable.columnCount() < 3):
            self.ElevatorTable.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.ElevatorTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.ElevatorTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.ElevatorTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.ElevatorTable.setObjectName(u"ElevatorTable")
        self.ElevatorTable.setGeometry(QRect(370, 120, 311, 181))
        self.ElevatorsSpinBox = QSpinBox(self.page_2)
        self.ElevatorsSpinBox.setObjectName(u"ElevatorsSpinBox")
        self.ElevatorsSpinBox.setGeometry(QRect(370, 50, 71, 31))
        self.ElevatorsSpinBox.setMinimum(1)
        self.ElevatorsSpinBox.setMaximum(8)
        self.ElevatorsSpinBox.setValue(2)
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(370, 30, 121, 16))
        self.AlgorithmComboBox = QComboBox(self.page_2)
        self.AlgorithmComboBox.setObjectName(u"AlgorithmComboBox")
        self.AlgorithmComboBox.setGeometry(QRect(70, 270, 161, 24))
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 250, 221, 16))
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(70, 300, 221, 16))
        self.ModelComboBox = QComboBox(self.page_2)
        self.ModelComboBox.setObjectName(u"ModelComboBox")
        self.ModelComboBox.setGeometry(QRect(70, 320, 161, 24))
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(70, 350, 221, 16))
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(70, 370, 41, 16))
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(140, 370, 51, 16))
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(120, 370, 16, 16))
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(200, 370, 16, 16))
        self.TrafficConfigurationButton = QPushButton(self.page_2)
        self.TrafficConfigurationButton.setObjectName(u"TrafficConfigurationButton")
        self.TrafficConfigurationButton.setGeometry(QRect(370, 320, 131, 31))
        self.stepCount = QLabel(self.page_2)
        self.stepCount.setObjectName(u"stepCount")
        self.stepCount.setGeometry(QRect(300, 120, 49, 16))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 20, 191, 61))
        font = QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.MenuButton_2 = QPushButton(self.page_3)
        self.MenuButton_2.setObjectName(u"MenuButton_2")
        self.MenuButton_2.setGeometry(QRect(260, 430, 101, 41))
        self.up_peak_button = QRadioButton(self.page_3)
        self.up_peak_button.setObjectName(u"up_peak_button")
        self.up_peak_button.setGeometry(QRect(80, 120, 92, 20))
        self.down_peak_button = QRadioButton(self.page_3)
        self.down_peak_button.setObjectName(u"down_peak_button")
        self.down_peak_button.setGeometry(QRect(80, 150, 92, 20))
        self.mixed_peak_button = QRadioButton(self.page_3)
        self.mixed_peak_button.setObjectName(u"mixed_peak_button")
        self.mixed_peak_button.setGeometry(QRect(80, 180, 92, 20))
        self.label_14 = QLabel(self.page_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(80, 90, 131, 16))
        self.intensitySpinBox = QDoubleSpinBox(self.page_3)
        self.intensitySpinBox.setObjectName(u"intensitySpinBox")
        self.intensitySpinBox.setGeometry(QRect(290, 120, 84, 23))
        self.intensitySpinBox.setDecimals(4)
        self.intensitySpinBox.setSingleStep(0.010000000000000)
        self.intensitySpinBox.setValue(0.050000000000000)
        self.label_15 = QLabel(self.page_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(230, 120, 50, 20))
        self.label_16 = QLabel(self.page_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(230, 90, 161, 16))
        self.SaveButton_2 = QPushButton(self.page_3)
        self.SaveButton_2.setObjectName(u"SaveButton_2")
        self.SaveButton_2.setGeometry(QRect(370, 430, 101, 41))
        self.back_to_config_button = QPushButton(self.page_3)
        self.back_to_config_button.setObjectName(u"back_to_config_button")
        self.back_to_config_button.setGeometry(QRect(80, 40, 79, 24))
        self.label_17 = QLabel(self.page_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(230, 150, 49, 16))
        self.seedSpinBox = QSpinBox(self.page_3)
        self.seedSpinBox.setObjectName(u"seedSpinBox")
        self.seedSpinBox.setGeometry(QRect(350, 150, 71, 20))
        self.traffic_stacked_widget = QStackedWidget(self.page_3)
        self.traffic_stacked_widget.setObjectName(u"traffic_stacked_widget")
        self.traffic_stacked_widget.setGeometry(QRect(420, 90, 261, 281))
        self.up_peak_page = QWidget()
        self.up_peak_page.setObjectName(u"up_peak_page")
        self.label_18 = QLabel(self.up_peak_page)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 20, 71, 16))
        self.arrval_floor_spin_box = QSpinBox(self.up_peak_page)
        self.arrval_floor_spin_box.setObjectName(u"arrval_floor_spin_box")
        self.arrval_floor_spin_box.setGeometry(QRect(90, 18, 51, 20))
        self.upPeakTable = QTableWidget(self.up_peak_page)
        if (self.upPeakTable.columnCount() < 2):
            self.upPeakTable.setColumnCount(2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.upPeakTable.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.upPeakTable.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        self.upPeakTable.setObjectName(u"upPeakTable")
        self.upPeakTable.setGeometry(QRect(10, 50, 241, 201))
        self.traffic_stacked_widget.addWidget(self.up_peak_page)
        self.down_peak_page = QWidget()
        self.down_peak_page.setObjectName(u"down_peak_page")
        self.label_19 = QLabel(self.down_peak_page)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 21, 101, 16))
        self.destination_floor_spin_box = QSpinBox(self.down_peak_page)
        self.destination_floor_spin_box.setObjectName(u"destination_floor_spin_box")
        self.destination_floor_spin_box.setGeometry(QRect(110, 20, 51, 20))
        self.traffic_stacked_widget.addWidget(self.down_peak_page)
        self.mixed_peak_page = QWidget()
        self.mixed_peak_page.setObjectName(u"mixed_peak_page")
        self.arrival_floor_spin_box_2 = QSpinBox(self.mixed_peak_page)
        self.arrival_floor_spin_box_2.setObjectName(u"arrival_floor_spin_box_2")
        self.arrival_floor_spin_box_2.setGeometry(QRect(110, 19, 51, 20))
        self.label_20 = QLabel(self.mixed_peak_page)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 20, 101, 16))
        self.destination_floor_spin_box_2 = QSpinBox(self.mixed_peak_page)
        self.destination_floor_spin_box_2.setObjectName(u"destination_floor_spin_box_2")
        self.destination_floor_spin_box_2.setGeometry(QRect(110, 50, 51, 20))
        self.label_21 = QLabel(self.mixed_peak_page)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 51, 101, 16))
        self.mixed_up_peak_ratio_spinbox = QDoubleSpinBox(self.mixed_peak_page)
        self.mixed_up_peak_ratio_spinbox.setObjectName(u"mixed_up_peak_ratio_spinbox")
        self.mixed_up_peak_ratio_spinbox.setGeometry(QRect(90, 120, 84, 23))
        self.mixed_up_peak_ratio_spinbox.setMaximum(1.000000000000000)
        self.mixed_up_peak_ratio_spinbox.setSingleStep(0.100000000000000)
        self.mixed_down_peak_ratio_spinbox = QDoubleSpinBox(self.mixed_peak_page)
        self.mixed_down_peak_ratio_spinbox.setObjectName(u"mixed_down_peak_ratio_spinbox")
        self.mixed_down_peak_ratio_spinbox.setGeometry(QRect(90, 150, 84, 23))
        self.mixed_down_peak_ratio_spinbox.setMaximum(1.000000000000000)
        self.mixed_down_peak_ratio_spinbox.setSingleStep(0.100000000000000)
        self.mixed_interfloor_peak_ratio_spinbox = QDoubleSpinBox(self.mixed_peak_page)
        self.mixed_interfloor_peak_ratio_spinbox.setObjectName(u"mixed_interfloor_peak_ratio_spinbox")
        self.mixed_interfloor_peak_ratio_spinbox.setGeometry(QRect(90, 180, 84, 23))
        self.mixed_interfloor_peak_ratio_spinbox.setMaximum(1.000000000000000)
        self.mixed_interfloor_peak_ratio_spinbox.setSingleStep(0.100000000000000)
        self.label_22 = QLabel(self.mixed_peak_page)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(60, 100, 41, 16))
        self.label_23 = QLabel(self.mixed_peak_page)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(8, 120, 71, 20))
        self.label_24 = QLabel(self.mixed_peak_page)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(8, 150, 71, 20))
        self.label_25 = QLabel(self.mixed_peak_page)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(8, 180, 71, 20))
        self.traffic_stacked_widget.addWidget(self.mixed_peak_page)
        self.randomButton = QCheckBox(self.page_3)
        self.randomButton.setObjectName(u"randomButton")
        self.randomButton.setGeometry(QRect(280, 150, 71, 20))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_13 = QLabel(self.page_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(270, 30, 171, 61))
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.settingsButton_2 = QPushButton(self.page_4)
        self.settingsButton_2.setObjectName(u"settingsButton_2")
        self.settingsButton_2.setGeometry(QRect(140, 400, 141, 41))
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.label_26 = QLabel(self.page_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(300, 30, 101, 61))
        self.label_26.setFont(font)
        self.label_26.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.resultsFileComboBox = QComboBox(self.page_5)
        self.resultsFileComboBox.setObjectName(u"resultsFileComboBox")
        self.resultsFileComboBox.setGeometry(QRect(40, 110, 261, 31))
        self.label_27 = QLabel(self.page_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(40, 90, 71, 16))
        self.acceptFilenameButton = QPushButton(self.page_5)
        self.acceptFilenameButton.setObjectName(u"acceptFilenameButton")
        self.acceptFilenameButton.setGeometry(QRect(310, 110, 41, 31))
        self.frame = QFrame(self.page_5)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(40, 200, 271, 201))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_29 = QLabel(self.frame)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 10, 49, 16))
        self.numberOfStepsAnalysis = QLabel(self.frame)
        self.numberOfStepsAnalysis.setObjectName(u"numberOfStepsAnalysis")
        self.numberOfStepsAnalysis.setGeometry(QRect(90, 10, 71, 16))
        self.label_30 = QLabel(self.frame)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 40, 61, 16))
        self.algorithmAnalysis = QLabel(self.frame)
        self.algorithmAnalysis.setObjectName(u"algorithmAnalysis")
        self.algorithmAnalysis.setGeometry(QRect(90, 40, 141, 16))
        self.label_32 = QLabel(self.frame)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 70, 101, 16))
        self.generatorAnalysis = QLabel(self.frame)
        self.generatorAnalysis.setObjectName(u"generatorAnalysis")
        self.generatorAnalysis.setGeometry(QRect(150, 70, 101, 16))
        self.label_31 = QLabel(self.frame)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 100, 91, 16))
        self.seedAnalysis = QLabel(self.frame)
        self.seedAnalysis.setObjectName(u"seedAnalysis")
        self.seedAnalysis.setGeometry(QRect(150, 100, 91, 16))
        self.label_39 = QLabel(self.frame)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(20, 130, 121, 16))
        self.label_40 = QLabel(self.frame)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 160, 101, 16))
        self.elevatorsAnalysis = QLabel(self.frame)
        self.elevatorsAnalysis.setObjectName(u"elevatorsAnalysis")
        self.elevatorsAnalysis.setGeometry(QRect(150, 130, 49, 16))
        self.floorsAnalysis = QLabel(self.frame)
        self.floorsAnalysis.setObjectName(u"floorsAnalysis")
        self.floorsAnalysis.setGeometry(QRect(150, 160, 49, 16))
        self.advancedAnalysis = QPushButton(self.frame)
        self.advancedAnalysis.setObjectName(u"advancedAnalysis")
        self.advancedAnalysis.setGeometry(QRect(180, 170, 79, 24))
        self.label_28 = QLabel(self.page_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(40, 180, 101, 16))
        self.frame_2 = QFrame(self.page_5)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(350, 200, 271, 201))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.label_34 = QLabel(self.frame_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 10, 111, 16))
        self.label_35 = QLabel(self.frame_2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 40, 111, 16))
        self.label_36 = QLabel(self.frame_2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(20, 70, 131, 16))
        self.label_37 = QLabel(self.frame_2)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(20, 100, 111, 16))
        self.label_38 = QLabel(self.frame_2)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(20, 130, 111, 16))
        self.journeyTime = QLabel(self.frame_2)
        self.journeyTime.setObjectName(u"journeyTime")
        self.journeyTime.setGeometry(QRect(160, 10, 49, 16))
        self.waitingTime = QLabel(self.frame_2)
        self.waitingTime.setObjectName(u"waitingTime")
        self.waitingTime.setGeometry(QRect(160, 40, 49, 16))
        self.travelTime = QLabel(self.frame_2)
        self.travelTime.setObjectName(u"travelTime")
        self.travelTime.setGeometry(QRect(160, 70, 49, 16))
        self.wTime = QLabel(self.frame_2)
        self.wTime.setObjectName(u"wTime")
        self.wTime.setGeometry(QRect(160, 100, 49, 16))
        self.nPassengers = QLabel(self.frame_2)
        self.nPassengers.setObjectName(u"nPassengers")
        self.nPassengers.setGeometry(QRect(160, 130, 49, 16))
        self.label_33 = QLabel(self.page_5)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(350, 180, 49, 16))
        self.backButton = QPushButton(self.page_5)
        self.backButton.setObjectName(u"backButton")
        self.backButton.setGeometry(QRect(50, 40, 79, 24))
        self.changeNamePushButton = QPushButton(self.page_5)
        self.changeNamePushButton.setObjectName(u"changeNamePushButton")
        self.changeNamePushButton.setGeometry(QRect(40, 143, 91, 24))
        self.reloadFilesPushButton = QPushButton(self.page_5)
        self.reloadFilesPushButton.setObjectName(u"reloadFilesPushButton")
        self.reloadFilesPushButton.setGeometry(QRect(140, 143, 79, 24))
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.traffic_stacked_widget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.startButton.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.settingsButton.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.reinforcementButton.setText(QCoreApplication.translate("MainWindow", u"Reinforcement Learning", None))
        self.analysePushButton.setText(QCoreApplication.translate("MainWindow", u"Analyse", None))
        self.SaveButton.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.MenuButton.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Number of floors", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Simulation steps", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Maximum number of people at the floor", None))
        self.VisualisationRadioButton.setText(QCoreApplication.translate("MainWindow", u"Visualisation", None))
        ___qtablewidgetitem = self.ElevatorTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Max people", None));
        ___qtablewidgetitem1 = self.ElevatorTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Speed", None));
        ___qtablewidgetitem2 = self.ElevatorTable.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Max floor", None));
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Number of elevators", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"AlgorithmEnum", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Model parameters:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Floors: ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Elevators:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u2013", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u2013", None))
        self.TrafficConfigurationButton.setText(QCoreApplication.translate("MainWindow", u"Traffic Configuration", None))
        self.stepCount.setText(QCoreApplication.translate("MainWindow", u"StepCount", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Traffic Configuration Panel", None))
        self.MenuButton_2.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.up_peak_button.setText(QCoreApplication.translate("MainWindow", u"Up-peak", None))
        self.down_peak_button.setText(QCoreApplication.translate("MainWindow", u"Down-peak", None))
        self.mixed_peak_button.setText(QCoreApplication.translate("MainWindow", u"Mixed-peak", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Traffic generation type:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Intensity:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Traffic generation parameters:", None))
        self.SaveButton_2.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.back_to_config_button.setText(QCoreApplication.translate("MainWindow", u"\u2190 Back", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Seed:", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Arrival floor:", None))
        ___qtablewidgetitem3 = self.upPeakTable.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Floor", None));
        ___qtablewidgetitem4 = self.upPeakTable.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Distribution", None));
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Destination floor:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Arrival floor:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Destination floor:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Ratios:", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Up-peak:", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Down-peak:", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Interfloor:", None))
        self.randomButton.setText(QCoreApplication.translate("MainWindow", u"random", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Reinforcement Learning", None))
        self.settingsButton_2.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Result analysis", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Results file:", None))
        self.acceptFilenameButton.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Steps:", None))
        self.numberOfStepsAnalysis.setText("")
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Algorithm:", None))
        self.algorithmAnalysis.setText("")
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Generation type:", None))
        self.generatorAnalysis.setText("")
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Generation seed:", None))
        self.seedAnalysis.setText("")
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Number of elevators:", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Number of floors:", None))
        self.elevatorsAnalysis.setText("")
        self.floorsAnalysis.setText("")
        self.advancedAnalysis.setText(QCoreApplication.translate("MainWindow", u"Advanced", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Simulation info:", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Mean journey time:", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Mean waiting time:", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Mean travel time:", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Wp:", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Passengers:", None))
        self.journeyTime.setText("")
        self.waitingTime.setText("")
        self.travelTime.setText("")
        self.wTime.setText("")
        self.nPassengers.setText("")
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Results:", None))
        self.backButton.setText(QCoreApplication.translate("MainWindow", u"\u2190 Back", None))
        self.changeNamePushButton.setText(QCoreApplication.translate("MainWindow", u"Change name", None))
        self.reloadFilesPushButton.setText(QCoreApplication.translate("MainWindow", u"Reload files", None))
    # retranslateUi

